### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by tkvogt** [reflex-frp/reflex-dom-ace#1]
A little hint how to add this to an existing relfex app would be nice.
So far I tried the following: Add the latest commit to stack.yaml
`packages:`
`- location:`
`    git: https://github.com/reflex-frp/reflex-dom-ace.git`
`    commit: b765e722764b74e20b82db77e8ca23cc3c0c0ba9`

Then add this code:

```haskell
elAttr "div" ("id" =: "editor") $ do
  text (T.pack "some code")`
  liftIO $ startACE (AceConfig "editor" (Map.fromList []) Nothing Nothing)
```
The browser then says: ace.edit can't find div #editor

**Comment by mightybyte** [comment]
I added a small example to the haddocks.  Hope that helps!
